# Generated by Django 4.0.6 on 2022-07-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
